### ISSUE TITLE
Add option to disable the notification "Tailwind config not found"

### ISSUE THREAD

**Issue by biati-digital** [Trapfether/tailwind-raw-reorder#10]
**Is your feature request related to a problem? Please describe.**
I usually open remote files to make some quick changes, every time I save I see this error https://share.cleanshot.com/TLFxxvzr activating/deactivating the extension makes no sense for this situations. Obviously on this cases a Tailwind config file does not exist but I'm fully aware of that.

**Describe the solution you'd like**
It would be great to have an option to disable that error "Tailwind config not found"

**Comment by Trapfether** [comment]
@biati-digital This has been implemented with a recent Merge Request. I'll be cutting a patch release on Friday that will make this option available to everyone. Please file another issue if you run into any other rough edges when using the plugin.

**Comment by Trapfether** [comment]
Going live with today's update. Please upgrade to the latest version to test it out
