### ISSUE TITLE
Allow custom class ordering.

### ISSUE THREAD

**Issue by irsyadpage** [Trapfether/tailwind-raw-reorder#13]
**Is your feature request related to a problem? Please describe.**
Is there any plan to allow for a custom class ordering?

**Describe the solution you'd like**
The [Headwind](https://github.com/heybourn/headwind) extenstion allows for custom sorting configuration via `headwind.defaultSortOrder` option. The [RustyWind](https://github.com/avencera/rustywind) tool also allow for custom sorter using `sortOrder` entry in the `config_file.json`.

[](https://github.com/heybourn/headwind/blob/master/package.json)

**Describe alternatives you've considered**
Is it possible for me to provide the [RustyWind](https://github.com/avencera/rustywind)'s `config_file.json` in here: https://github.com/Trapfether/tailwind-raw-reorder/blob/c73fe6e5d3ce6cce5a62bc811a2a7226589a58e8/src/index.mjs#L119-L122

**Comment by Trapfether** [comment]
@irsyadpage I'm sorry, but I don't intend to support custom ordering at this time. The reasoning is that this extension will automatically identify every tailwind class by tapping into your local tailwind install and config. This allows it to grab even one-off classes like bg-[#ffff00] automatically. The order is determined by the order in which the class is applied by tailwind, so later classes override earlier ones (if they overlap). How this should interact with custom ordering is non-trivial and prone to disagreement. Whether custom ordering should disable automatic discovery, whether classes covered by the custom order should be ordered according to the custom order and all other classes fall back to their automatic ordering (and how to deal with the unstable sort that is prone to occur in that case).

If you would like to fork this repo and change how it orders for your own usage, I encourage you to do so. The sorting is managed within the /src/sorting.mjs file. You can adapt those functions to take a specified config file and experiment with different approaches of blending the custom order with automatic class identification (or disable automatic identification all together). The repo is already set up for testing, debugging, and packaging as an extension and VSCode allows you to install an extension from a local package. I'd be happy to give you some additional guidance if you decide to go that route.

I'll leave this issue open for a few weeks to gather feedback. Perhaps someone has a better idea about how to support custom ordering such that it won't cause extensive disagreements going forward.

**Comment by irsyadpage** [comment]
> @irsyadpage I'm sorry, but I don't intend to support custom ordering at this time. The reasoning is that this extension will automatically identify every tailwind class by tapping into your local tailwind install and config. This allows it to grab even one-off classes like bg-[#ffff00] automatically. The order is determined by the order in which the class is applied by tailwind, so later classes override earlier ones (if they overlap). How this should interact with custom ordering is non-trivial and prone to disagreement. Whether custom ordering should disable automatic discovery, whether classes covered by the custom order should be ordered according to the custom order and all other classes fall back to their automatic ordering (and how to deal with the unstable sort that is prone to occur in that case).

Good considerations on the possible circumstances.

For the repo fork, I'm not planning to go to that route right now. Maybe one day if it became neccessary, I will reach you.

Thank you for the feedback 👍.
