### ISSUE TITLE
Error msg: Cannot find module @tailwindcss/typography

### ISSUE THREAD

**Issue by wshayes** [Trapfether/tailwind-raw-reorder#2]
**Describe the bug**
When trying to run - Tailwind Raw Reorder on a single file using the Meta-P Run Command option - I get the following error msg:

```
Cannot find module '@tailwindcss/typography'
Require stack:
- /Users/william/code/appkb/tailwind.config.js
```

I have a tailwind.config.js in the top-level directory, tailwindcss installed. I can run tailwind -m to minify the content which suggests that my tailwind.config.js is correct. I see the typography module installed in node_modules/@tailwindcss/typography

**To Reproduce**
1. Run Tailwind Raw Reorder: Sort Tailwind CSS Classes on a file in Visual Studio Code
2. Error msg pops up: 

```
Cannot find module '@tailwindcss/typography'
Require stack:
- /Users/william/code/appkb/tailwind.config.js
```

**Desktop (please complete the following information):**
 - OS: MacOS 14.0
 - Env: Visual Studio Code
 - Version: VSC 1.83 and today's version of tailwind-raw-reorder

**Additional context**

**Comment by Trapfether** [comment]
Thank you for bringing this to my attention. I'm going to do some digging tomorrow. I suspect that the module resolution is not computing to the correct destination folder since we are loading the local tailwind instead of using a stated dependency.

**Comment by Trapfether** [comment]
It was indeed a module resolution issue. It appears that commit e40622e has fixed the issue and I have cut a new version of the extension 3.0.3.

If you face any other troubles, please file another issue so I can take a look. Thank you for taking the time to let me know about this issue.
