### ISSUE TITLE
How to configure sorting order?

### ISSUE THREAD

**Issue by macCesar** [Trapfether/tailwind-raw-reorder#3]
With the way you handle RegEx, I was able to:

1. Sort `xml` files.
2. Also be able to sort `class` AND `classes`.

I achieved this using the following configuration:

```json
"tailwind-raw-reorder.classRegex": {
  "xml": [
    [
      "[class|classes]=(([\"'`])(?:(?:[^{}<>](?!\\2))|\\\\\\2)+[^{}<>])\\2",
      "[\"'`]([^]+)"
    ]
  ]
}
```

One thing I noticed is the sorting order difference between your extension and Headwind:

```javascript
// Tailwind Raw Reorder
class="rounded-16 mx-auto h-16 w-16"
// with FontAwesome classes
class="fas fa-phone-alt mr-1 flex-1 text-xs text-gray-600"

// Headwind
class="w-16 h-16 mx-auto rounded-16"
// with FontAwesome classes
class="flex-1 mr-1 text-xs text-gray-600 fas fa-phone-alt"
```

Did you notice how the spacing and sizing classes come first in the list in Headwind?

How can I configure `Tailwind Raw Reorder` to sort them in the same way?

Thank you!

**Comment by Trapfether** [comment]
@macCesar This repo uses the approach that the prettier plugin does. That is it hooks into your local copy of tailwind (or the included dependency if the local tailwind can't be found) and uses it to assign orders. This gets around the issue with the Headwind where you had to constantly maintain your list of selectors and headwind had no support for computed selectors "w-[5px]" for example. You would always have to add these to your list of selectors. The benefit of the tailwind established order is that later selectors override earlier ones if there is any overlap in properties assigned.

Custom class names are sorted first so they don't get lost at the tail end of a long list of classes.

**Comment by macCesar** [comment]
Thanks @Trapfether ... 👍🏼 

I got used to the new sorting order!! 😀
