### ISSUE TITLE
It does not work with *.css.

### ISSUE THREAD

**Issue by gomo** [Trapfether/tailwind-raw-reorder#5]
**Describe the bug**

I may be setting it up wrong, but it didn't work with the CSS file.

**To Reproduce**
1. I have set the following in tailwind.config.js
```js
/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ['app/views/**/*.html.erb', 'app/frontend/**/*.css'],
  plugins: [require('@tailwindcss/typography'), require('@tailwindcss/forms')],
};
```
2. And in .vscode/setting.json
```json
  "tailwind-raw-reorder.classRegex": {
    "css": "\\B@apply\\s+([\\._a-zA-Z0-9\\s\\-\\:\\/]+);"
  }
```
4. Save `app/frontend/entrypoints/base.css`
```css
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';

@layer components {
  .foobar {
    @apply right-0 absolute;
  }
}
```
6. But absolute did not move front.

The following `*.html.erb` file works fine and moves the `absolute` to the front.

```html.erb
  <div
    class="right-0 absolute z-10 mt-2 hidden w-56 origin-top-right rounded-md bg-slate-800 shadow-lg ring-1 ring-black ring-opacity-5 transition duration-100 ease-out focus:outline-none"
    role="menu"
    aria-orientation="vertical"
    aria-labelledby="menu-button"
    tabindex="-1"
  >
    <div class="py-1" role="none"><%= yield %></div>
  </div>
```

**Desktop (please complete the following information):**

macOS 13.4 (22F66)

vscode
```
Version: 1.84.2 (Universal)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:33.687Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.5.0
```

Tailwind Raw Reorder v3.0.3

**Comment by Trapfether** [comment]
I am checking into this. I can't seem to replicate at this moment, going to borrow a mac and see if I am able to replicate the issue.

**Comment by Trapfether** [comment]
@gomo could you update to the latest version and try again?

If it does not happen automatically, could you trigger the Tailwind Raw Reorder: Sort Tailwind CSS Classes command from the command window when you have the css file open? That should let us know if the sorter is breaking on the css file itself or if it is running successfully but not recognizing the apply rule for some reason.

I have not had any luck replicating this issue as of yet

**Comment by gomo** [comment]
@Trapfether 

Thanks for trying to reproduce my problem.

I tried again and the reordering still did not happen with the CSS file.

One thing I noticed is that when I open vscode settings from the menu and click `Edit in settings.json` under `Css Regex` section, the default settings are copied to `.vscode/settings.json`. When I save it, I get an error `Tailwind Raw Reorder: Tailwind config not found`. Even though the tailwind.config.js is in the root of the workspace and everything else is working fine.

If you cannot reproduce this, it may be a conflict with some other extension.

I am now sorting the CSS file classes by `prettier-plugin-tailwindcss`.

If I notice anything else, I will comment again, but I may not be able to reply much as I have been busy with work lately. It doesn't seem to be happening to anyone else, and if you can't reproduce it, you can close this ISSUE.
